networks:
  portainer-network:
    name: docker-vlan
    external: true
  internal-network:
    driver: bridge

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    networks:
      internal-network:
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

  nginx:
    image: nginx:alpine
    container_name: portainer-proxy
    networks:
      portainer-network:
        ipv4_address: x.x.21.1
      internal-network:
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - portainer