networks:
  host-network:
    name: docker-vlan
    external: true
  internal-network:
    driver: bridge


services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    networks:
      internal-network:
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: homeassistant-proxy
    networks:
      internal-network:
      host-network:
        ipv4_address: x.x.21.6
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - homeassistant