networks:
  portainer-network:
    name: docker-vlan
    external: true

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    networks:
      portainer-network:
        ipv4_address: x.x.21.2
    volumes:
      - ./data:/home/node/.n8n
      - ./cert:/home/node/.cert
      - ./output:/opt/output
    environment:
      N8N_SECURE_COOKIE: "false"
      WEBHOOK_URL: "https://n8n.local"
      N8N_PROTOCOL: "https"
      N8N_PORT: 443
      N8N_SSL_CERT: "/home/node/.cert/cert.pem"
      N8N_SSL_KEY: "/home/node/.cert/key.pem"
      N8N_RUNNERS_ENABLED: "true"
    restart: unless-stopped