networks:
  portainer-network:
    name: docker-vlan
    external: true
  internal-network:
    driver: bridge


services:
  opnsocks:
    image: onixldlc/opnsocks:latest
    container_name: opnsocks
    cap_add:
      - NET_ADMIN
    networks:
      internal-network:
    environment:
      - CONFIG_BASE64=${CONFIG_BASE64}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: opnsocks-proxy
    networks:
      portainer-network:
        ipv4_address: x.x.21.5
      internal-network:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - opnsocks
    restart: unless-stopped